### ISSUE TITLE
pg_restore and psql version are not the same on Rstudio and python environnement

### ISSUE THREAD

**Issue by JackLemaitre** [InseeFrLab/images-datascience#141]
```
R:
pg_restore --version
pg_restore (PostgreSQL) 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
Python
pg_restore --version
pg_restore (PostgreSQL) 15.4
```

**Comment by avouacr** [comment]
Indeed. It is not the case in all our Python images, only in the ones based on the python-datascience image. The reason is that a Python package in our datascience environment has Postgresql as dependency, and the last version packaged on Pandas is much newer than the one in apt's repositories. 

I guess we could add the PostgreSQL repository (https://computingforgeeks.com/install-and-configure-postgresql-on-ubuntu/) to our [install-system-libs.sh](https://github.com/InseeFrLab/images-datascience/blob/main/scripts/install-system-libs.sh) script to download the latest version in all images. The versions won't be exactly matched this way, but it will already be much closer. @JackLemaitre interested in doing a PR for this ?
