### ISSUE TITLE
Using a custom image in pod setup

### ISSUE THREAD

**Issue by fBedecarrats** [InseeFrLab/images-datascience#228]
The current r-datascience image includes old GDAL and PROJ versions. @avouacr indicated a way to install updated ones at startup (#215), but I see that the process is very long and sometimes fail. For the training I am facilitating I would need a more straightforward way to have an environment that work for my purpose.
There is a custom image that fits my need available at `ghcr.io/mapme-initiative/mapme-spatial:1.4.0` (source Dockerfile accessible here), but when I include in the pod setup as follows:
![image](https://github.com/user-attachments/assets/ef591fad-371c-499d-adc0-c2483d3b1b37)
the pod launch fails at all attempt.
Am I doing something wrong when trying to use a custom image?

**Comment by avouacr** [comment]
Hi @fBedecarrats, I understand your need for more recent versions of geospatial libraries. However, I don't think we want to integrate this upgrade process directly in our images. The philosophy of the images-datascience project is to provide users with images that fit most datascience purposes while building reliably each week. Having the latest versions of geospatial libraries is an advanced use, and would both add maintenance costs on our side and risk reducing the stability of the pipeline in comparison to relying on rocker's build scripts.

That being said, this is something you can definitely build for yourself in order to tailor our services to your needs. if the procedure I suggested in #215 takes too long / is not reliable enough in the context of an init script, then the relevant solution is likely to use a custom image, as you suggested. You won't be able to use any custom image from other producers because our [helm-charts](https://github.com/InseeFrLab/helm-charts-interactive-services) rely on precise configuration found in our images. I would encourage you to build your own custom image that inherits ours, tweak the environment to fit your needs, test the image in our services like you tried with the `mapme-spatial` one, and then make your trainees use this custom service (which can be provided as a single custom URL precising the custom image).

So in practice, you would follow a procedure that looks somewhat like this : 

- on your dockerhub account, initialize a repository my_dh_account/my_repo

- on your GitHub account, initialize a repository that will serve to build your custom image with a CI job, with two files :

A `Dockerfile` that would look something like this : 

```Dockerfile
FROM inseefrlab/onyxia-r-datascience:r4.4.1

# Some shell code that upgrades the relevant geospatial libraries, and potentially install additional R packages
# See #215 for inspiration
```

A `.github/workflows/build.yaml` with this [content](https://github.com/docker/build-push-action?tab=readme-ov-file#git-context), adapted to the name of your DH repo of course, and with relevant token provided as secrets on the GH repository.

So quite a simple repository all things considered, which with a litte bit of trial and error would lead you to a custom image fitting your needs, and directly usable as custom image in our services.

Good luck!

**Comment by fBedecarrats** [comment]
Thanks a lot for the feedback @avouacr ! 
I [refined the init script](https://github.com/BETSAKA/Tools/blob/main/init_scripts/Improved_sequence.sh) and I have the impression that it works better now. I will try to do it with this init script today as I have to rush for the training now and I'll try to develop the Dockerfile tonight. Thanks again!

**Comment by fBedecarrats** [comment]
Hello @avouacr , we finished the training with the init solution. I will have to focus on other emergencies for the coming week and I hope to  work on this custom image in December. Feel free to close the issue if you see fit. Thanks again!
